name: Auto Update Ygosu Dashboard

on:
  schedule:
    - cron: '*/30 * * * *' # ★ 30분마다 알아서 실행 (원하는 주기로 변경 가능)
  workflow_dispatch: # 수동으로 즉시 실행하고 싶을 때 쓰는 버튼 활성화

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/configure-pages@v3
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Crawler Script
      run: python main.py

    - name: Commit and Push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.io"
        git add index.html ygosu_prev_rank.csv ygosu_prev_rank_receive.csv
        git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-update rankings" && git push)
